colors vividchalk
set guifont=Meslo\ LG\ S\ DZ:h16
set transparency=6

" Hide the toolbar by default
set guioptions-=T

" Hide scrollbars
set guioptions-=r
set guioptions-=L

" hi ColorColumn guibg=#202020
