#!/bin/sh

set -e

session_to_end=$(tmux list-panes -F "#S")

function session_to_use {
  tmux ls -F "#{session_name}" | grep -v "${session_to_end}" | head -1
}

tmux switch -t "$(session_to_use)"
tmux kill-session -t "${session_to_end}"
