#!/bin/bash
# Usage: git boost
# Rebases the current branch on top of latest origin/master (by fetching it
# first).

set -e

default_branch_name="${GIT_DEFAULT_BRANCH:-master}"

if [[ "$1" == "squash" ]]; then
  autosquash="--autosquash --interactive"
else
  autosquash="--no-autosquash"
fi


if [[ "${branch_name}" == "${default_branch_name}" ]]; then
  echo "Can't boost $branch_name."
  exit 1
fi

git fetch
git rebase $autosquash "origin/$default_branch_name"
