#!/bin/bash
# Usage: git boost
# Rebases the current branch on top of latest origin/master (by fetching it
# first).

set -e

default_branch_name="${GIT_DEFAULT_BRANCH:-master}"

if [[ "${branch_name}" == "${default_branch_name}" ]]; then
  echo "Can't boost $branch_name."
  exit 1
fi

git fetch origin "$default_branch_name:$default_branch_name"
git rebase "origin/$default_branch_name"
