#!/usr/bin/env sh

set -e

branch_name="$(git symbolic-ref HEAD 2>/dev/null)"
branch_name=${branch_name##refs/heads/}

git fetch

if [[ "${branch_name}" == "master" ]]; then
  echo "Can't do this on master."
  exit 1
fi

git checkout master
git pull --ff-only
git branch -d "${branch_name}"
