#!/usr/bin/env bash

set -e

branch_name="$(git symbolic-ref HEAD 2>/dev/null)"
branch_name=${branch_name##refs/heads/}

if [[ "${branch_name}" == "master" ]]; then
  echo "Can't do this on master."
  exit 1
fi

git checkout master
git branch -D "${branch_name}"
