#!/usr/bin/env bash

set -euo pipefail

domain=${1}
domain=${domain#https}
domain=${domain#http}
domain=${domain#://}

curl --insecure -v "https://${domain}" 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
