#!/usr/bin/env bash

# http://serverfault.com/a/661982

set -e 

server=$1

echo | openssl s_client -showcerts -servername "$1" -connect "${1}:443" 2>/dev/null | openssl x509 -inform pem -noout -text
