"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Miha Filej"
email = "miha@filej.net"

[aliases]
difft = [
  "--config",
  "ui.diff-formatter='difft --color=always $left $right'",
  "diff",
]

[ui]
editor = "nvim"
pager = "delta"
default-command = "log"
merge-editor = ":builtin"
diff-editor = ":builtin"
diff-formatter = ":git"

[revset-aliases]
"immutable_heads()" = "builtin_immutable_heads() | (trunk().. & ~mine())"

[git]
write-change-id-header = true

[templates]
git_push_bookmark = '"mfi-" ++ change_id.short()'
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  surround(
    "\nJJ: ignore-rest\n", "",
    diff.git(),
  ),
)
'''
