"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Miha Filej"
email = "miha@filej.net"

[aliases]
difft = [
  "--config",
  "ui.diff-formatter='difft --color=always $left $right'",
  "diff",
]

[colors]
"diff token" = { underline = false }

[ui]
editor = "nvim"
pager = "delta"
default-command = "log"
merge-editor = ":builtin"
diff-editor = ":builtin"
diff-formatter = ":git"

[revset-aliases]
"immutable_heads()" = "builtin_immutable_heads() | (trunk().. & ~mine())"
'why_immutable(r)' = 'r | roots(r:: & immutable_heads())'
"private()" = 'subject(regex:"^\\[")'
"shelved()" = 'subject(regex:"^\\[[~-][[:word:]]+\\]")'
"pushable()" = "~private()"

[git]
write-change-id-header = true

[templates]
git_push_bookmark = '"mfi-" ++ change_id.short()'
draft_commit_description = "builtin_draft_commit_description_with_diff"
log = "builtin_log_compact ++ if(!description && !empty, diff.summary())"

[template-aliases]
'format_short_signature(signature)' = 'coalesce(signature.name(), signature.email().local(), email_placeholder)'
'format_timestamp(timestamp)' = '''
if(
  timestamp.after("6 days ago"),
  timestamp.ago(),
  timestamp.local().format("%Y-%m-%d %H:%M:%S"),
)
'''

[merge-tools.zed]
program = "zed"
diff-args = ["--diff", "$left", "$right"]

[merge-tools.difft-inline]
program = "difft"
diff-args = ["--color=always", "--display=inline", "--width=$width", "$left", "$right"]

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]

[merge-tools.delta-preview]
program = "/Users/miha/bin/jjui-delta-preview"
diff-args = ["revision", "$left", "$right"]
diff-expected-exit-codes = [0, 1]

[merge-tools.delta-file-preview]
program = "/Users/miha/bin/jjui-delta-preview"
diff-args = ["file", "$left", "$right"]
diff-expected-exit-codes = [0, 1]

[gg.ui]
recent-workspaces = ["/Users/miha/Developer/gem/gem-server"]
