"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Miha Filej"
email = "miha@filej.net"

[aliases]
difft = ["--config", "ui.diff.tool='difft --color=always $left $right'", "diff"]

[ui]
editor = "nvim"
pager = "delta"
default-command = "log"
merge-editor = ":builtin"
diff-editor = ":builtin"

[ui.diff]
format = "git"

[revset-aliases]
"envs()" = "tags(regex:'^(production|staging|preview)$')"
"immutable_heads()" = "builtin_immutable_heads() & ~envs()"

[git]
push-bookmark-prefix = "mfi-"

[templates]
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  surround(
    "\nJJ: ignore-rest\n", "",
    diff.git(),
  ),
)
'''
